DB_PATH = "db/chroma_db"
COLLECTION_NAME = "personal_notes"

DOCS_PATH = "docs"

TOP_K = 5

CHUNK_SIZE = 700
CHUNK_OVERLAP = 150

EMBEDDING_MODEL = "BAAI/bge-small-en-v1.5"

MODEL = "llama-3.3-70b-versatile"
TEMPERATURE = 0.2
MAX_TOKENS = 800

SHOW_SOURCES = True
DEBUG_GRAPH = True

MEMORY_DB_PATH = "db/memory_chroma_db"
MEMORY_COLLECTION_NAME = "fact_memory"
MEMORY_TOP_K = 3
MEMORY_SIMILARITY_THRESHOLD = 0.55